repos:
-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.3
    hooks:
    -   id: ruff
        args: [--fix, --exit-non-zero-on-fix]
-   repo: https://github.com/psf/black
    rev: 24.4.2
    hooks:
    -   id: black
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.10.0
    hooks:
      - id: mypy
        args: [
            --config-file=.mypy.ini,
            --namespace-packages,
            --ignore-missing-imports,
            --no-strict-optional,  
            --explicit-package-bases,
            --follow-imports=silent,
            --ignore-missing-imports
        ]
        additional_dependencies: ['types-requests']
        exclude: ^(model_zoo/.*|tasks/.*)$
